name: Post Today's Wordle in a GIF
on:
  schedule:
    - cron:  '21 13 * * *'
jobs:
  wordle-in-gif:
    name: Wordle in GIF
    runs-on: ubuntu-latest
    env:
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: python -m src.run
